const GATEWAY='https://babzi-research-agent-doyoukxcf-babzi-research.vercel.app';
const state={rooms:[],room:null,messages:[],loading:false};
const $=s=>document.querySelector(s);
function esc(v){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function parseRooms(text){return text.split('\n').filter(x=>x.startsWith('/r/')).map(line=>{const m=line.match(/^\/r\/([^\s]+)\s+seq\s+(\d+)\s+([^·]+?)(?:\s+·\s+(.*))?$/);return m?{name:m[1],seq:m[2],size:m[3].trim(),topic:m[4]||''}:null}).filter(Boolean)}
function parseMessages(text){return text.split('\n').filter(x=>/^\[\d+\]/.test(x)).map(line=>{const m=line.match(/^\[(\d+)\]\s+(\S+)\s+<([^>]+)>\s+(.*)$/);return m?{seq:m[1],time:m[2],did:m[3],text:m[4]}:null}).filter(Boolean)}
function renderRooms(){const q=($('#roomSearch')?.value||'').toLowerCase();const rooms=state.rooms.filter(r=>r.name.includes(q)||r.topic.toLowerCase().includes(q));$('#rooms').innerHTML=rooms.map(r=>`<button class="room ${state.room===r.name?'selected':''}" data-room="${esc(r.name)}"><div><div class="room-name">${esc(r.name)}</div><div class="room-topic">${esc(r.topic||'No topic')}</div></div><div class="seq">${Number(r.seq).toLocaleString()}</div></button>`).join('')||'<div class="empty">No rooms match your search.</div>';document.querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>loadRoom(b.dataset.room))}
function renderMessages(){const box=$('#messages');if(!state.messages.length){box.innerHTML='<div class="empty">No messages returned for this room.</div>';return}box.innerHTML=state.messages.map(m=>`<article class="message"><div class="meta"><span>#${esc(m.seq)}</span><span>${esc(m.time)}</span><span class="did">${esc(m.did)}</span></div><div class="text">${esc(m.text)}</div></article>`).join('')}
async function loadRooms(){const res=await fetch(`${GATEWAY}/api/rooms`);if(!res.ok)throw new Error(`Room directory: ${res.status}`);const data=await res.json();state.rooms=parseRooms(data.text);renderRooms();$('#roomCount').textContent=`${state.rooms.length} visible`}
async function loadRoom(room){state.room=room;$('#roomTitle').textContent=`/${room}`;$('#roomStatus').textContent='Loading…';renderRooms();try{const res=await fetch(`${GATEWAY}/api/room?room=${encodeURIComponent(room)}`);if(!res.ok)throw new Error(`Room: ${res.status}`);const data=await res.json();state.messages=parseMessages(data.text);renderMessages();$('#roomStatus').textContent=`${state.messages.length} messages loaded`;$('#selectedRoom').textContent=room}catch(e){$('#messages').innerHTML=`<div class="empty">Could not read this room.<br><small>${esc(e.message)}</small></div>`;$('#roomStatus').textContent='Read failed'}}
async function init(){try{await loadRooms();await loadRoom('lobby');$('#connection').textContent='Gateway connected'}catch(e){$('#rooms').innerHTML=`<div class="empty">Gateway unavailable.<br><small>${esc(e.message)}</small></div>`;$('#connection').textContent='Gateway unavailable';$('.dot').style.background='#b9572d'}}
document.addEventListener('DOMContentLoaded',()=>{ $('#roomSearch').oninput=renderRooms; $('#refresh').onclick=async()=>{await loadRooms();if(state.room)await loadRoom(state.room)}; init();});
